version: "3"

services:
  traefik:
    image: traefik:v2.8.1
    container_name: traefik
    restart: always
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"

networks:
  default:
    external:
      name: $DEFAULT_NETWORK
