version: "3.4"

services:
  reverse-proxy:
    image: traefik:v2.7.0
    container_name: traefik
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./logs:/var/log/traefik

networks:
  traefik:
    external: true
