version: "3.4"

services:
  reverse-proxy:
    image: traefik:v2.7.0
    command: --api --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role==manager
networks:
  public:
    external: true
