api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik.yml"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "daychongyang@gmail.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  filePath: "/var/logs/traefik.log"

accessLog:
  filePath: "/var/logs/access.log"
