api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik.yml"

log:
  level: INFO
  filePath: "/var/logs/traefik.log"

accessLog:
  filePath: "/var/logs/access.log"
