// Jenkinsfile (Declarative Pipeline)
pipeline {
    //  Defining execution environments 
    agent {
        docker {
            image 'node:lts'
        }
    }

    stages {
        stage('Install') {
            steps {
                sh 'node --version'
            }
        }

        stage('Build') { 
            steps {
                echo 'Build'
            }
        }
        
        stage('Deliver') { 
            steps {
                echo 'Deliver'
            }
        }
    }
}
